output_dir: /app/snapshots
db_path: /app/data/sources.db
sources:

web:
  host: 0.0.0.0
  port: 8091
  auto_refresh_seconds: 30
  max_index_items: 10000

filenames:
  timezone: Europe/London
  pattern: "%Y/%m/%d/%Y-%m-%d_%H-%M-%S.jpg"
